import hexmap_generator as hg

# Path to the hexagon IDs file generated by app.py
HEX_FILE = "chicago_hex_ids.txt"

# Output file for the map
OUTPUT_FILE = "chicago_hexmap_example.html"

def main():
    """
    Example of creating a map from a list of hexagons.
    """
    print(f"Creating a map from hexagons in {HEX_FILE}")
    
    success = hg.map_from_hexfile(
        hex_file=HEX_FILE,
        output_file=OUTPUT_FILE,
        title="Chicago Hexagons Example Map",
        colorscale="Plasma"  # Using a different colorscale as an example
    )
    
    if success:
        print(f"Map successfully created and saved to {OUTPUT_FILE}")
    else:
        print("Failed to create map")

if __name__ == "__main__":
    main() 